name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - develop  # Change to 'master' if your default branch is master
  workflow_dispatch:   #  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push to gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          
      - name: Build MkDocs via Makefile
        working-directory: docs              # run make from the docs/ folder
        run: make build                      # 
  
          
      - name: Build and Deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          # Optional: Extra requirements file if you have one
          # EXTRA_PACKAGES: build-base
